If:
  # For C files
  PathMatch: .*\.c$
CompileFlags:
  Compiler: x86_64-w64-mingw32-gcc
  Add:
    - -D__CLANG_MAX_ALIGN_T_DEFINED
    - -Wno-vla-extension
    - -nostdinc
    - -IC:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/14.1.0/include
    - -IC:/msys64/mingw64/x86_64-w64-mingw32/include
    - -IC:/msys64/mingw64/include
    - -DLOCAL
    - -Wall
    - -O2
    - -Wextra
    - -Wshadow
    - -Wconversion
    - -Wfloat-equal
    - -Wno-unused-const-variable
    - -Wno-sign-conversion
    - -std=c23

If:
  # For C++ files
  PathMatch: .*\.cpp$
CompileFlags:
  Compiler: x86_64-w64-mingw32-g++
  Add:
    - -D__CLANG_MAX_ALIGN_T_DEFINED
    - -nostdinc++
    - -IC:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/14.1.0/include/c++
    - -IC:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/14.1.0/include/c++/x86_64-w64-mingw32
    - -IC:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/14.1.0/include
    - -IC:/msys64/mingw64/include
    - -DLOCAL
    - -Wall
    - -O2
    - -Wextra
    - -Wshadow
    - -Wconversion
    - -Wfloat-equal
    - -Wno-unused-const-variable
    - -Wno-sign-conversion
    - -std=c++23

Index:
  Background: Skip

